### ISSUE TITLE
Ignore PhantomData in derive

### ISSUE THREAD

**Issue by Studiedlist** [BenHall-7/diff-struct#18]
As far as I understand, it is not possible to derive diff on struct with `PhantomData` field(s). 
It might be reasonable to just ignore `PhantomData` (and maybe some other types?) in order to make it possible to derive `Diff`

**Comment by benhall-7** [comment]
Since the derive macro expects the fields in the struct to match the fields in the derived diff struct, it probably just needs a placeholder. If the struct has PhantomData meant to ignore some unused type parameter, then I'll probably also need to include the PhantomData in the diff, because when the diff uses the type parameter the same way it'll also need the PhantomData

**Comment by benhall-7** [comment]
https://github.com/benhall-7/diff-struct/commit/56fc4a7840eb4ecd5df7da1a309ee6deea606f91
