### ISSUE TITLE
Q: purpose of `Diff::identity`?

### ISSUE THREAD

**Issue by target-san** [BenHall-7/diff-struct#23]
Hello!

Not that I object it, though purpose of `Diff::identity() -> Self` which in fact duplicates `Default::default` is a bit unclear. IMO it's irrelevant for diffable type whether it can be default or identity constructed or not.

Thanks

**Comment by benhall-7** [comment]
Hello! I created it as a kind of solution to a problem with diffing certain types. When you add a key, value pair to a HashMap<K, T>, or insert an element into a Vec<T>, I wanted the resulting diff type to use T::Repr, and not T itself. Basically, in any situation where a value "appears" instead of "changes", I need to create a value of type T that I can apply the diff T::Repr to to produce the final object. For example, consider:

```rust
let before: Option<char> = None;
let diff: <Option<char> as Diff>::Repr = OptionDiff::Some(Some('a'));
let after = before.apply_new(&diff);
```

So I need a value that can stand in for T and produce the desired result. Maybe a more general solution would be to simply add more type constraints, like requiring that T implements Default in Options, HashMaps, etc. I'll consider changing that if/when I make some substantial changes the crate

**Comment by target-san** [comment]
Looking at your crate and `structdiff` (kind of competitor), I though about trait like this:
```
trait Diff {
    type Repr; // No additional reqs like Clone, Default, Eq etc.

    fn diff(&self, other: &Self) -> Option<Self::Repr>; // Returning `Option<Self::Repr>` allows caller code to easily know whether diff is empty, without more constraints on `Self::Repr`
    
    fn apply(&mut self, diff: Self::Repr); // Accepting `Self::Repr` by value removes need for `Self::Repr: Clone` constraint
}
```
And move all specific constraints to type impls.
The other thing I stumbled upon is that `Diff` macro generates diff structs in such a way that there's no way to know whether specific field changed or not - if field type's `Repr` doesn't have easily distinguishable "zero" state.

Thanks for clarification
